== Derivation

There are two types of derivation in Ngujari. The first, lexical
derivation, is not applicable _generally_, and is instead used during
word formation to derive new vocabulary. While the patterns are regular,
the application is not. On the other hand, general derivation allows the
modification of existing words, including changing part of speech (such
as in verb nominalisation).

=== Lexical Derivation

==== Verbs

As verb roots are a closed class, derivation is the only way to form new
verbs. This method is known as _compounding_.

===== Compounding

There are two forms of compounding: verb-verb and adverb-verb. Both form
a new verb which is treated as a whole in syntactic structures.

In verb-verb compounding, the compound is not commutative, meaning that
the order of the verbs matters. Typically, the most relevant verb occurs
last. The two verbs are simply concatenated, except for the special case
in which the concatenation would form an illegal consonant cluster. If
this occurs, the repair strategy of inserting the dummy vowel _a_ is
used.

====
to sit _walj_ +
to swim _junn_ +
⇒ to canoe _waljunn_

to travel _nuunn_ +
to exchange _murr_ +
⇒ to trade (with another mob) _nuunnamurr_
====

Verbs formed through verb-verb compounding in most cases assume the
transitivity properties of the second, or primary, verb.

Adverb-verb compounding simply requires an adverb to appear before the
verb in all positions. For example, it would remain in front of the verb
during relativization (see *relative clauses* while regular adverbs
would not.

====
to run _yaj_ +
quickly _garrna_ +
⇒ to sprint _garrna yaj_

to drink _ngann_ +
impatiently _karlpii_ +
⇒ to guzzle _karlpii ngann_
====

A common use of adverb-verb compounding is in augmentation and
diminution. The adverbs _purki_ ("weakly") and _puwa_ ("strongly") are
used to modify the intensity of the verb.

====
to eat _jinn_ +
⇒ to nibble _purki jinn_ +
⇒ to bite _puwa jinn_

to give _gulwaj_ +
⇒ to offer _purki gulwaj_ +
⇒ to force upon _puwa gulwaj_
====

==== Nouns

There are many noun derivational operations.

===== Compounding

Nominal compounds are bidirectional, meaning that the order of
constituent nouns does not change the meaning of the compound. In
practical use, both orders are used, with preference depending on the
phonetics of the noun. If the compounding would create an illegal
consonant cluster, the other order must be used.

====
mountain _gaypa_ +
stream _munna_ +
⇒ mountain stream _gaypamunna_

the Land _Yawirra_ +
ground _nnalu_ +
⇒ sacred place _Yawirrannalu_
====

===== Collection

Partial reduplication can be used to derive the collection of a noun. To
derive the collection, the first syllable is isolated, its coda removed,
and added to the front of the noun.

====
coconut _wurna_ +
⇒ coconut tree _wuwurna_

bone _parrna_ +
⇒ corpse _paparrna_
====

===== Container

The container of a noun can be derived through the affix _rna_.

====
arrow _yungi_ +
⇒ quiver _yungirna_

fruit _yirli_ +
⇒ basket _yirlinga_
====

==== Adjectives

===== Cases

Noun case suffixes can in some cases be used to derive adjectives based
around that noun. The most common forms of case derivations are
orientative/revertive and instrumental.

Orientative and revertive suffiixs can be used to indicate the
"direction" of an adjective in relation to its noun. This distinction is
commonly found when talking about time.

====
age _jul_ +
⇒ new _jurni_ (orientative) +
⇒ old _julnga_ (revertive)

freshness _gurlu_ +
⇒ fresh _gurlurni_ +
⇒ stale _gurlunga_
====

=== General Derivation

==== Adjectives

===== Negation

An adjective can be negated through a prefix. If the adjective begins
with a stop, the prefix is _wuu_. Otherwise, it is _tu_.

====
long (distance) _yungi_ +
⇒ short (distance) _tuyungi_

heavy (rain) _ganu_ +
⇒ light (rain) _wuuganu_
====

===== Amplification

An adjective can be amplified in magnitude through reduplication. The
final syllable is duplicated, excluding its coda in the first instance.
If the final vowel is long following the derivation, it becomes
shortened.

====
big _yampu_ +
⇒ enormous _yampupu_

small _pangii_ +
⇒ tiny _pangiigi_

thick _yurlan_ +
⇒ fat _yurlarlan_
====

===== Relativisation

Many of Ngujari's adjectives are absolute rather than relative. For
example, _yampu_ ("big") refers to something bigger than a human, rather
than something big for its class (as in "the big elephant"). These
absolute adjectives can be converted to relative adjectives through the
suffix _pu_.

====
small (absolute) _pangii_ +
⇒ small (relative) _pangiipu_

warm (absolute) _mirra_ +
⇒ warm (relative) _mirrapu_
====

==== Nouns

For all general derivations of nouns, the noun must be placed into
derived form by lengthening its final vowel (if the vowel is
unlengthened). A modifying suffix is then appended.

===== Diminuation/Amplification

A noun's _scale_ can be adjusted up or down through the following
suffixes:

.Scale derivational suffixes
[options="header"]
|=======================
| function      | suffix
| amplification | rki
| diminuation   | wa
|=======================

This operation is commonly lexicalised, but can be applied generally.

====
fire _panwa_ +
⇒ ash _panwawa_ +
⇒ bushfire _panwarki_

wind _gaju_ +
⇒ breath _gajuwa_ +
⇒ high wind _gajurki_
====

===== Temporalisation

A noun can be modified into a temporal noun, meaning the equivalent of
"time of noun", using the suffix _ku_.

====
moon _tii_ +
⇒ night _tiiku_

sun _puu_ +
⇒ day _puuku_
====

==== Verbs

===== Nominalisation

Apart from the gerund formation process (see *gerunds*), verbs may
become nouns through the process of nominalisation. The nominal form is
simply the verb with its final vowel added to its end and shortened,
plus the relevant suffix.

For locational nouns, as in "place of verb", the suffix is _nnalu_
("ground").

====
to see _pirr_ +
⇒ eye _pirrinnalu_

to hold _wuj_ +
⇒ hand _wujunnalu_
====

For professional nouns, as in "person who does verb", the suffix is
_ngu_.

====
to swim _junn_ +
⇒ swimmer _junnungu_

to sleep _tarr_ +
⇒ sleeper _tarrangu_
====
