== Other verb and verb-phrase operations

=== Nominalisation

A verb is nominalised by adding its final vowel and a relevant suffix.

==== Action nominalisation

Action nominalisation occurs when a verb is nominalised to a gerund, a noun representing its action. This nominalisation is usually morphological, being a standard derivation of the verb class, but in some exceptions is lexical.

The gerund of a verb serves two purposes. It can act in a way similar to
the English gerund, where the verb is used as a noun, or in a way
similar to an infinitive, meaning roughly "in order to".

The gerund is formed through nominalising the verb. The last vowel of
the verb is simply appended as a suffix.

When used in the nominal form, the gerund takes the appropriate noun
case.

====
_like.aux-rem 1s-erg swim.ger-abs like-an-1st_ +
I used to like swimming.
====

When used in the infinitive form, the overlap relationship is used in a clause chain.

====
_3s-ERG go-3-an-SS hunt.ger-ABS do-an-3rd_ +
He went there to hunt. (lit he went to do hunt)
====

==== Participant nominalisation

Ngujari supports agent nominalisation, in which the verb is nominalised to refer
to its agent. This is an almost completely productive operation.

In an agent nominalisation, there is no distinction between "classes" (e.g.
runner) and "events" (e.g. the person currently running.)

// TODO: add exceptions from lexicon

The suffix _ngu_ (person) is added to nominalise the verb. The resulting noun is always of the animate gender when deciding morphological endings and the alignment of the phrase.

====
_arrive.AUX-PST bake-NOMINALISE-ERG arrive-3-an late_ +
The baker was late
====

Instrument nominalisation is a syntactic process, that uses the demonstrative
pronoun as a clause's agent.

====
_DEMPRON-INAN-ERG coffee.ABS grind-INAN-3RD_ +
coffee grinder (lit. "that which grinds coffee")

_break.AUX-PST 1s.an-ERG DEMPRON-INAN-ABS break-1-an, comp DEMPRON-INAN-ERG coffee.ABS grind-INAN-3RD_
I broke the coffee grinder
====

The verb must be in the present tense.

Locational nominalisation uses the suffix _nnalu_ (ground). A nominalised
location implicitly takes locative case, and is not marked if it does so. It can
be marked for revertive or orientative, but can take no other cases.

====
_go.AUX-PRES-WIMP 1pl.an-ERG bury-LOCATION go-1-an_ + 
Let's go to the graveyeard

_go.AUX-PRES-WIMP 1pl.an-ERG bury-LOCATION-REV go-1-an_ + 
Let's leave the graveyeard
====

// TODO: table here showing which operations are productive and exceptions

=== Compounding

Compounding is a lexical operation used when forming new verbs. There are two forms of compounding: verb-verb and adverb-verb. Both form
a new verb which is treated as a whole in syntactic structures.

In verb-verb compounding, the compound is not commutative, meaning that
the order of the verbs matters. Typically, the most relevant verb occurs
last. The two verbs are simply concatenated, except for the special case
in which the concatenation would form an illegal consonant cluster. If
this occurs, the repair strategy of inserting the dummy vowel _a_ is
used.

====
to sit _walj_ +
to swim _junn_ +
⇒ to canoe _waljunn_

to travel _nuunn_ +
to exchange _murr_ +
⇒ to trade (with another mob) _nuunnamurr_
====

Verbs formed through verb-verb compounding in most cases assume the
transitivity properties of the second, or primary, verb.

Adverb-verb compounding simply requires an adverb to appear before the
verb in all positions. For example, it would remain in front of the verb
during relativization (see *relative clauses*) while regular adverbs
would not.

====
to run _yaj_ +
quickly _garrna_ +
⇒ to sprint _garrna yaj_

to drink _ngann_ +
impatiently _karlpii_ +
⇒ to guzzle _karlpii ngann_
====

A common use of adverb-verb compounding is in augmentation and
diminution. The adverbs _purki_ ("weakly") and _puwa_ ("strongly") are
used to modify the intensity of the verb.

====
to eat _jinn_ +
⇒ to nibble _purki jinn_ +
⇒ to bite _puwa jinn_

to give _gulwaj_ +
⇒ to offer _purki gulwaj_ +
⇒ to force upon _puwa gulwaj_
====

=== Tense/aspect/mode

Tense refers to the time at which the verb's action took place. There
are four marked tenses: remote past, past, present, and future.

Present is considered the default tense. It usually indicates those
events which are happening in the moment of utterance, but it can also
be used as a rudimentary form of a near-past tense, applying to actions
that were completed the same day as the utterance.

====
_come.aux-pres rain.cloud-erg int-1pl-ori come-an-1st_ +
Are the rain clouds drawing near?

_give.aux-pres 1s-nom 3s.inan-com 3s.an-acc give-an-1st_ earlier +
I gave it to him earlier today.
====

The past tense simply refers to an event that began and concluded in the
past. If the event has not yet concluded, the present tense is used,
even if it began in the past.

====
_1pl-ERG see-an-1st-DS kangaroo-ERG hop-an-3rd_ +
We saw the hopping kangaroo.
====

The remote past also indicates an event that was completed in the past.
The distinction between it and the standard past can be somewhat
arbitrary, but in general remote past is used in the following three
circumstances:

* recounting handed-down stories
* speaking of ancestral events
* referring to a habitual action that has concluded

====
_shine.aux-rem sun-erg Bilru-abs shine-an-3rd_ +
The sun shone down on Bilru.

_be.aux-rem hut-erg mountain-loc be-inan-3rd_ +
The hut used to be on the hill.
====

The future tense refers to all events which are yet to take place,
regardless of how far in the future they occur.

====
_go.aux-fut neg 1s-erg there go-an-1st_ +
I won't go there.
====

==== Aspect

Aspect refers to the definiteness of an action. The perfective aspect
refers to events which are complete and self-contained ("I ran"),
whereas the imperfective aspect refers to ongoing events ("I was
running"). In Ngujari, there is no morphological distinction drawn
between the perfective and imperfective aspects, meaning contextual
clues are vital for understanding.

====
_1s-erg butterfly-abs see-an-1st-SS be.aux-pst forest-loc be-an-1st_ +
I was looking at a butterfly when I was in the forest.

_1s-erg butterfly-abs see-an-1st-SS blush.aux-pst blush-an-1st_ +
I saw a butterfly that made me blush.
====

==== Moods

A mood modifies the meaning of a verb. Verbs can be conjugated into one
of five moods:

* subjunctive
* weak imperative
* strong imperative
* gnomic
* dubitative

Mood is an optional part of verb formation. In a regular active
sentence, there is no mood.

====
_↗ eat.aux-pres 1pl-nom eat-an-1st_ +
Should we eat?
====

But adding a mood, such as the imperative, changes the meaning of the
sentence.

====
_eat.aux-pres-wimp 1pl-nom eat-an-1st_ +
Let's eat.

_eat.aux-pres-strimp 1pl-nom eat-an-1st_ +
We must eat.
====

===== Subjunctive

The subjunctive mood is an _irrealis_ mood: it broadly signifies
abstractness, or that the speaker is unsure about the event in question.

The subjunctive is used in four places:

1. Speculation
2. Desires
3. Negatives
4. Conditional

The negative and conditional cases are related to syntax, and are
discussed later.

The most common semantic use of the subjunctive mood is speculation. It indicates that a speaker
is either unsure of an event's outcome, or does not know if it occurred
or will occur.

====
_kill.AUX-PST-SUBJ 3s-ERG kangaroo-ABS kill-AN-3RD_ +
He might have killed the kangaroo.

_COMP-walk-pst-subj 3pl.ch-ERG place-ORI walk-ch-3rd know-an-1st_ +
I think that they came back yesterday.
====

The subjunctive is also used when expressing desires or dreams. The
desire must be first-hand; so recounting those of others does not use
the subjunctive.

====
_want.AUX-PRES-SUBJ 1s-ERG bed-ABS want-AN-1st_ +
I want a new bed.

_say.AUX-PST 3s-NOM 1s-ACC say-AN-3rd, want.AUX-PRES 1s-ERG bed-ABS want-AN-1st_ +
He said to me, "I want a new bed."
====

===== Imperative

The imperative mood is used for suggestions and commands. The weak
imperative raises an idea or suggestion, without indicating an order,
similar to the English "let's go".

====
_cut.AUX-FUT-WIMP neg 1pl-erg tree-ABS  cut-an-1st_ +
Let's not cut down the tree.
====

The strong imperative signifies a command, such as "Leave!".

====
_cut.AUX-FUT-STRIMP neg 2s-erg tree-abs cut-an-2nd_ +
Don't cut down the tree.
====

===== Gnomic

The gnomic mood states unequivocal facts or ideas. The statement must be
truly uncontentious to fit into the gnomic mood, a universal truth or
maxim.

====
_fly.aux-pres-gno bowerbird-PL-ERG east-LOC fly-an-3rd winter-adv_ +
Satin bowerbirds fly east for winter.
====

===== Dubitative

The dubitative mood indicates situational possibility. The speaker
acknowledges the possibility of an action but is unsure as to whether it
occurs. This is similar to English sentences using the auxiliary
"might".

====
_rain.aux-fut-dub rain-an-3rd_ +
It might rain tomorrow.
====

=== Participant Reference

Verbs reference subject person and number through suffixes.

There are three situations in which participant reference is anaphoric (and the
verb can stand alone without a noun phrase subject).

1. Intransitive clauses where the reference has been preestablished.

    ====
    _... ? cry-AN-3RD_ +
    What does the monkey do? It cries.
    ====

2. Or where the subject is an animate pronoun.

    ====
    _cry-AN-3RD_ +
    He cries.
    ====

3. In the main clause of a clause chain, where the subject is an animate pronoun
     and the only explicit argument to the final verb.

In other cases, participant reference is purely grammatical and the agreeing
noun phrase must be present.