== Pragmatically marked structures

=== Pragmatic statuses

=== Focus, contrast, topicalisation

Topicalisation is the process of fronting a noun phrase for emphasis, indicating
the topic of the sentence. Topicalisation occurs through left-dislocation:  the
noun phrase elevated is moved to the front of the sentence, seperated with a
pause, before the sentence runs as usual but with a pronoun (personal?)
corefering back to the dislocated noun phrase. The fronted noun is marked for
case, but the corefering pronoun is not.

====
_[kangaroo-ABS]i kill.AUX-PST 1S-ERG [3S-INAN]i kill-AN-1ST_ +
As for the kangaroo, I killed it.
====

Topicalisation is permitted only for noun phrases that are not the subject.

// TODO: does this satisfy the downplaying centrality of A requirement?

// TODO: starred incorrect example

=== Negative

A negative simply inverts the meaning of a part of a sentence.

Clausual negation is expressed through both analytic and morphological markings.

To form the clausal negative, the negative particle must be
used footnote:[The negative particle corresponds to the class of the
clause's verb. See the morphology chapter for more.].

In a standard negative clause, the particle follows the auxiliary of the
verb.

====
_go.aux neg 3s.an-erg there go-an-3rd_ +
He doesn't go there.
====

However, the mood of the negative sentence must be subjunctive, if in any
non-present tense.

// TODO: add example

However, in an imperative clause (one that uses the weak or strong imperative
mood, see *tense and mood*), the particle is instead placed before the
auxiliary, and the subjunctive is not used.

// TODO: add example

There are two negative particles; one for predicate nominals (all classes), the
other for all other sentences (_tuu_).

In all clausal negatives, _qualifiers_ can be used as stand-alone
utterances, which follow the sentence. A qualifier is a word such as
_wulnni_ ("never") which modifies the negative.

====
*ti j-i-yuu ku-j waa yanj-awu-n wulnni* +
_neg steal.aux-strimp 2s-nom 3.val.1 steal-an-2nd never_ +
You must never steal.
====

==== Derivational negation

An adjective can be negated through a prefix. If the adjective begins
with a stop, the prefix is _wuu_. Otherwise, it is _tu_.

====
long (distance) _yungi_ +
⇒ short (distance) _tuyungi_

heavy (rain) _ganu_ +
⇒ light (rain) _wuuganu_
====

=== Non-declarative speech acts

==== Interrogative

_Interrogatives_ are simply questions. There are two types of
interrogatives:

* _Polar_, which have an affirmative or negative answer.
* _Non-polar_, which require a more detailed response.

===== Polar

Polar questions are extremely easy to form, and are marked only by intonation. They are expressed as a
factual statement, but with a rising tone at the beginning of the
question.

====
*nn-uuki kupa-kupa-ø gaypa-gaypa-rn narnn-u-m?* +
_↗ fly.aux-fut bird-pl-erg mountain-pl-loc fly-an-3rd_ +
Will the birds fly to the mountains?
====

===== Question-word questions

The primary way of forming a non-polar question is through the use of
interrogative pronouns (such as _piima_), which replace the questioned word in-situ. The interrogative takes the
place of a noun in a verb phrase, but is not assigned a case.

====
*k-a pii munnanna-rn wa-yi naa wiirr-u-m* +
_go.aux-pst who river-loc 1s.an-com 2.val.3 go-an-3rd_ +
Who went to the river with me?
====

This method of questioning can be used in any type of sentence, not just
basic clauses. The following example shows its use in a locational
predicate which contains a relative clause. The interrogative pronoun,
_kiru_, is moved to the front of the sentence to highlight its
importance.

====
*kiru ngarr-i wumpa-ø j-i palyaj-a-m nnu-ø wurlki-j ngurr-a-m* +
_where be.aux-pres path-erg leadto.aux-prs leadto-inan-3rd 3s.inan-erg village-nom be-inan-3rd_ +
Where is the path that leads to the village?
====

A less-common way to ask a non-polar question requires the particle
_yuu_. By placing the particle ahead of a word in a statement, the
speaker questions that word.

====
*k-aa yuu-nnara-ø nurtwu-j panwa-rnu mirr-uu-m* +
_bring.aux-fut int-3dual.an-erg food-nom fire-ori bring-ch-3rd_ +
Will it be those two children who bring the food to the fire?

*nn-i wa-ø yuu-gurlurni parnti-j jinn-u-mi* +
_eat.aux-pres 3s-erg int-fresh kangaroomeat-nom eat-an-3rd_ +
Is the kangaroo meat he is eating fresh?
====
