== Pragmatically marked structures

=== Topicalisation

Topicalisation is the process of fronting a noun phrase for emphasis, indicating
the topic of the sentence. Topicalisation occurs through left-dislocation:  the
noun phrase elevated is moved to the front of the sentence, seperated with a
pause, before the sentence runs as usual but with a personal pronoun
corefering back to the dislocated noun phrase. The fronted noun is marked for
case, but the corefering pronoun is not.

====
_[kangaroo-ABS] kill.AUX-PST 1S-ERG [3S.INAN] kill-AN-1ST_ +
As for the kangaroo, I killed it.
====

Topicalisation is permitted only for noun phrases that are the object of the sentence.

====
fish-ABS eat.AUX-FUT 1s-ERG [3S.INAN] eat-an-1st +  
As for the fish, I will eat it

(INC) 1s-ERG  eat.AUX-FUT [1S.AN] fish-ABS eat-an-1st +
As for me, I will eat the fish
====

=== Negative

A negative simply inverts the meaning of a part of a sentence.

Clausal negation is expressed through both analytic and morphological markings, and negates the whole clause.

To form the clausal negative, the negative particle must be
used footnote:[The negative particle corresponds to the class of the
clause's verb. See the morphology chapter for more.].

There are two negative particles; one for predicate nominals (all classes), the
other for all other sentences (_tuu_).

In a standard negative clause, the particle follows the auxiliary of the
verb.

====
_3s.an-erg there go-an-3rd_ +
He goes there

_go.aux-pres neg 3s.an-erg there go-an-3rd_ +
He doesn't go there.
====

For predicate nominals, the particle is at the beginning of the sentence.

====
_neg 1S-ERG baker-ABS_ +
I am not a baker.

_neg 1s-ERG baker-ABS cop-PST_ +
I was not a baker.
====

==== The use of the subjunctive in forming negatives

If a sentence is in any non-present tense, the mood of the negative sentence must be subjunctive.

====
_go.aux-fut 3s.an-erg there go-an-3rd_ + 
He will go there tomorrow

_go.aux-fut-subj neg 3s.an-erg there go-an-3rd_ +
He won't go there tomorrow
====

The mood is also subjunctive if the negative is used when responding to a question with a speech act.

====
_take.aux-pres who money-ABS to.completion take-3-an_ +
Who is taking all the money?

_be.aux-pres-subj 1s.an-NOM be-INTRANS-1-an_ +
Not me (lit. I be not)
====

However, in an imperative clause (one that uses the weak or strong imperative
mood, see *tense and mood*), the particle is instead placed before the
auxiliary, and the subjunctive is not used.

====
_ride.AUX-STRIMP 2s.an-ERG bike-ABS ride-1-an_ +
Don't ride your bike!
====

In all clausal negatives, _qualifiers_ can be used as stand-alone
utterances, which follow the sentence. A qualifier is a word such as
_wulnni_ ("never") which modifies the negative.

====
_steal.aux-strimp neg 2s-nom steal-intrans-an-2nd never_ +
You must never steal.
====

// TODO add some more qualifiers

==== Derivational negation

An adjective can be negated through a prefix. If the adjective begins
with a stop, the prefix is _wuu_. Otherwise, it is _tu_.

====
long (distance) _yungi_ +
⇒ short (distance) _tuyungi_

heavy (rain) _ganu_ +
⇒ light (rain) _wuuganu_
====

=== Non-declarative speech acts

==== Interrogative

_Interrogatives_ are simply questions. There are two types of
interrogatives:

* _Polar_, which have an affirmative or negative answer.
* _Non-polar_, which require a more detailed response.

===== Polar

Polar questions are extremely easy to form, and are marked only by intonation. They are expressed as a
factual statement, but with a rising tone at the beginning of the
question.

====
_↗ fly.aux-fut bird-pl-erg mountain-pl-loc fly-an-3rd_ +
Will the birds fly to the mountains?
====

===== Question-word questions

The primary way of forming a non-polar question is through the use of
interrogative pronouns (such as _piima_), which replace the questioned word in-situ. The interrogative takes the
place of a noun in a verb phrase, but is not assigned a case.

====
_go.aux-pst who river-loc 1s.an-com go-an-3rd_ +
Who went to the river with me?
====

This method of questioning can be used in any type of sentence, not just
basic clauses. The following example shows its use in a locational
predicate which contains a relative clause. The interrogative pronoun,
_kiru_, is moved to the front of the sentence to highlight its
importance.

====
_be.aux-pres where path-erg be-3-inan [COMP dempron.inan.s-ERG village-abs leadto-inan-3rd]_ +
Where is the path that leads to the village?
====

The gender and number agreement of the verb is determined by that of the coreferring interrogative pronoun.

A less-common way to ask a non-polar question requires the particle
_yuu_. By placing the particle ahead of a word in a statement, the
speaker questions that word.

====
_bring.aux-fut int-3dual.an-erg food-nom fire-ori bring-ch-3rd_ +
Will it be those two children who bring the food to the fire?

_3s.erg kangaroomeat-nom eat-an-3rd [COMP DEMPRON-inan-3rd-abs] freshness-com_ +
Is the kangaroo meat he is eating fresh? (lit. He is eating kangaroo meat, is it with freshness?)
====
