== Predicate nominals and related constructions

=== Predicate nominals

A predicate nominal is a construction that exresses one of two meanings:

- proper inclusion
- equative predicates

==== Proper inclusion

Proper inclusion indicates that a noun is a member of a class, such as a
profession or a nationality.

In the present tense, a proper inclusion predicate is formed through adjacent
noun phrases, with no copula.

====
_1S-ERG teacher-ABS_ +
I am a teacher.
====

However, if the predicate is in another tense, _ngarr_, the auxiliary of _ngurr_
(to be) is used as a copula. It is declined according to tense, but not mood,
and follows the noun phrases.

====
_1S-ERG teacher-ABS COP-PST_ +
I was a teacher.
====

==== Equative predicates

An equative predicate signifies that two nouns corefer, in that they reference
the same object. They are formed using the verb _ngurr_ (to be), which acts as a
copula.

====
_1S-NOM 2S-ACC be-AN-1ST copula_ +
I am your friend.
====

// TODO: include quantifier details here from existing info

=== Predicate adjectives

Predicate adjectives assign an adjective to describe a noun phrase. They are
formed in the same way as a proper inclusion noun predicate.

Before they can be used as predicates, adjectives must be inflected.
They are lexicalised as verbs, and agree with the gender of the
predicate phrase's subject.

To decline a predicate adjective, two steps are required:

1.  If the adjective ends in a vowel, its last consonant is added to the
end. Otherwise, it is unmodified.
2.  The relevant gender suffix of a class one verb is added as a suffix.

There is another form of adjectival predicate, in which a noun is used
in place of an adjective. While this may seem counterintuitive, the noun
in effect becomes an adjective. This form is used when describing a
changeable state. The described noun is treated as above, but the
modifying noun is given the comitative case.

====
*murta-j gurlu-yi* +
_berry-nom freshness-com_ +
The berry is fresh.
====

=== Predicate locatives

Predicate locatives assign a noun phrase to a location. They are formed in the
same way as a proper inclusion noun predicate. The location comes after the
noun, and is placed in the locative case.

=== Existentials

The existential predicate is formed through a copula taking one argument, the
existing verb. The copula, _gunn_ (TODO: add to dictionary), is declined as an
auxiliary for tense only; excepting the present tense, which is unmarked.

The copula appears after the noun which "exists". The noun phrase takes the
comitative case.

====
_beach-COM COP_ +
There is a beach / A beach exists.
====

The copula does not act as a verb and hence cannot take adjuncts. Instead,
clause chaining provides a means for supplying adjuncts.

====
_beach-COM COP-SS DEMPRON-LOC village-LOC adjoin/abut-AN-3RD_ +
There is a beach near the village / The village has a beach.
====


When preceding a clause chain, the subject is _not_ elided and placed in the
main clause. It remains in position before the copula, which is marked with the
SS modifier. Inside, the _uninflected_ demonstrative pronoun corefers with the
existing noun phrase.

Inside an existential, the noun phrase can include adjectives and relative
clauses as normal.

====
_beach-COM long COP, COMP 1S-ERG DEMPRON-AN-1-ABS want-AN-1ST_ +
There's a long book that I want.
====

Negative existentials are a seperate construction. They are formed through
negative locative possession, with the dummy subject being the locative
demonstrative _naarla_ (there).

====
_NEG doorknob-ERG DEM.LOC.1 be-INAN-3RD_ +
There's no doorknob / lit. The doorknob is not on there.

_be.AUX-PST NEG bag-PL-ERG DEM.LOC.PL be-INAN-3RD_ +
There weren't any bags.
====

=== Possessive clauses

There are three types of possession in the Ngujari language.

The first two are distinguished by their changeability. _Alienable
possession_ isn't permanent, and is subject to change, whereas
_inalienable possession _cannot be changed. The difference between the
two revolves around culture, and is outlined in *possession*.

The third type is _group possession_, in which something is owned by
the tribe as a whole. This is formed in a different way to the first
two.

==== Alienable

Alienable possession is either _locative-based_ or _pronominal_.

In locative-based possession, the verb _ngurr_ is used. The possessed
noun becomes the agent of the verb, while the possessor is given the
locative case. Unusually, this means that the verb does not have a noun
in the object case, even though its valence remains the same.

Locative-based possession can be thought of as a noun being on
somebody's person. Where in English we might say "I have a spear", the
literal Ngujari translation is closer to "The spear is on me", even if
the spear is in fact kilometres away. This can be seen in the following
example.

====
*ngarr-i mulu-mulu-ka-ø mungu-rn ngurr-a-m* +
_be.aux-pres deadfish-pl-dual-erg woman-loc be-inan-3rd_ +
The woman has two dead fish.
====

The second form of the alienable possession, pronominal possession, is
described in the noun chapter.

==== Inalienable

Inalienable possession is indicated through the use of the verb
_gurr_. The possessor becomes the agent and the possessed noun becomes
the object.

====
*garr-aa-nga ngungu-ø jarta-j ka gurr-u-ø* +
_have.aux-fut-gno mob-erg homeland-nom 3.val.2 have-an-1st_ +
Our mob will always have a homeland.
====

It is important to note that _gurr_ is by default trivalent, meaning it
takes three nouns: an agent, an object, and a _manner_. The manner is
a noun in the comitative case, and describes the means by which the noun
became or is possessed. The following example is the same as the above,
except a manner is specified.

====
*garr-aa-nga ngungu-ø jarta-j yuurrpa-yi ka gurr-u-ø* +
_have.aux-fut-gno mob-erg homeland-nom courage-com 3.val.2 have-an-1st_ +
Our mob will always have a homeland, due to our courage.
====

==== Group

In Ngujari culture, an object can be owned by a mob as a whole. With the
exception of areas of land, only inanimate nouns may be possessed by a
mob.

Group possession is formed using the special particle _tuu_, which
appears before the noun. To specify the possessing mob, the mob's name
is placed immediately after the particle.

====
*nn-i-ju waya-ø tuu-Gurnu jaku nnalu-j muu-ma naa tinn-u-ø* +
_protect.aux-strimp 1pl-erg pos-gurnu precious land-nom spirit-inst 2.val.3 protect-an-1st_ +
We must protect our [the Gurnu mob's] precious land with vigour.
====

The regular name is used by members of the possessing mob, but the
honorific name is used for possessions of others footnote:[Culture
dictates that each mob has two names: an "insider" name and an
"outsider" name. To use the insider name without being a member of the
mob is a grave offence.]. For example, the combined particle for
something owned by the Wujanga mob would be _tuu-Wujanga_ for a member
or _tuu-Wujarra_ for an outsider.
