== Semantics

=== Colours

In Ngujari, colours are derived from nouns through the suffix _ku_.
There are six primary colours, detailed in the following table, along
with their base noun.

.Colours
[options="header"]
|===================================
| colour | word    | noun  | meaning
| black  | nguku   | ngu   | person
| white  | tumwaku | tumwa | sand
| red    | wirraku | wirra | blood
| green  | nurku   | nurli | seaweed
| yellow | puuki   | puu   | sun
|===================================

Additional colours can be formed either through compounding or modifying
a new noun. All colours can be joined with others to form compounds.

====
black _nguku_ +
white _tumwaku_ +
⇒ grey _nguku-tumwaku_

sunset _kii_ +
⇒ orange _kiiku_
====

=== Kinship

The kinship system of Ngujari revolves around four _totems_. The
population is split into four:

* _bilru_ (seal)
* _gunya_ (black wallaby)
* _juunwi_ (satin bowerbird)
* _pilkiya_ (platypus)

The pattern of totem inheritance is rigid but simple, with a woman of a
specific totem obliged to partner with a man of another prescribed totem
to produce offspring of an entirely different totem. However, the
inheritance is ultimately cyclic.

.Totem inheritance
[options="header"]
|==============================
| man     | woman   | offspring
| bilru   | gunya   | pilkiya
| gunya   | bilru   | juunwi
| juunwi  | pilkiya | gunya
| pilkiya | juunwi  | bilru
|==============================

Closely related to the totem system is the _nnurru_, a term for a
sacred place for all those members of a single totem. In contrast,
_Yawirrannalu_ (sacred place) is sacred for all Ngujari.

Many kinship terms are relative to totem. Of note is the fact that there are
different terms for children, depending on whether the speaker is themselves a
child. A selection of kinship terms that are independent of totem (by necessity
of the inheritance pattern) is presented in the table below:

.Kinship terms
[options="header"]
|=======================================
| word     | relation
| wirrangu | parent, male or female
| mulyi    | mother
| wiilyu   | father
| giirki   | offspring, baby (lit. seed)
|=======================================
