== Voice and valence adjusting operations

=== Valence and predicate calculus

A verb's _valence_ determines the number of arguments it can take. For
example, a verb with a valence of two would take two nouns:

====
*k-a nnalji-ø pijtu-j nirr-u-m* +
_fight.AUX-PST dingo-ERG snake-NOM fight-AN-3RD_ +
The dingo fought the snake.
====

In addition to their valence, the arguments to verbs have restrictions
on their case. For the majority of transitive verbs, with a valence of
two, the arguments take the form of a subject and object. The cases are
determined by the alignment of the sentence.

However, this can differ, and some verbs have irregular argument cases.
This is especially true in the case of verbs relating to movement, which
instead take a subject and a location.

====
*j-a wa-ø gaypa-rn yaj-awu-ø* +
_run.aux-pst 1s-erg mountain-loc run-an-1st_ +
I ran to the mountain [and ended up there].
====

When verbs take an argument in the locative case, the speaker can
instead use the revertive or orientative case for further control over
meaning.

====
*j-a wa-ø gaypa-rnu yaj-awu-ø* +
_run.aux-pst 1s-erg mountain-ori run-an-1st_ +
I ran towards the mountain

*j-a wa-ø gaypa-rna yaj-awu-ø* +
_run.aux-pst 1s-erg mountain-rev run-an-1st_ +
I ran away from the mountain
====

All verbs have a _default valence_: the number of arguments it takes
without modification. Most verbs are transitive, but valences can span
between avalent (taking no arguments) and quadrivalent (taking four).

==== Common Verb Valences

For each of the seven verbs with irregular auxiliaries, the different
possible valences and according arguments are shown below. The default
valence appears in bold. The argument markers SUBJ and OBJ refer to the
subject and object respectively, which differs according to alignment.

* _ngurr_: *(2) SUBJ is OBJ*
* _gulwaj_: (2) SUBJ gives to OBJ; *(3) SUBJ gives COM to OBJ*
* _gurr_: (2) SUBJ has OBJ; *(3) SUBJ has OBJ in COM
manner*footnote:[For an example of the use of the comitative slot, see
the constituent negative in the syntax chapter.]
* _nnurr_: *(2) SENTENCE causes SENTENCE* footnote:[The verb _nnurr_
is a special case. See the subjunctive section.]
* _wann_: *(1) SUBJ knows*; (2) SUBJ knows OBJ; (3) SUBJ knows OBJ
because of INST
* _yurr_: *(1) SUBJ knows*; (2) SUBJ knows OBJ; (3) SUBJ knows OBJ
on the authority of COM
* _girr_: *(1) SUBJ senses something*; (2) SUBJ feels that
SENTENCE footnote:[Where the sentence is in the subjunctive mood.]


=== Valence increasing operations

==== Applicatives

For a transitive verb, it is common to find a configuration with a third
argument in an applicative case, representing the means with which the
action occurred. The verb's valency is therefore increased, making it ditransitive.

When using the applicative, the cases of the existing subject and object are unchanged, as is the verb. The only indication of the construction is the presence of the declined third argument.

The applicative cases are:

* instrumental
* comitative
* locative
* orientative
* revertive

// Example

==== Causatives

There are two forms of the causative. The _nominative causative_ occurs for
direct causation when a single noun is responsible for causing a verb phrase to
occur. However, if an entire verb phrase is responsible, or the causation is
more indirect, clause chaining is used.

===== Nominative causative

When a noun phrase is responsible for the action taking place, the nominal
causative is used.

The operation occurs morphologically. The auxiliary of the verb phrase receives
the causative suffix _ji_ (TODO: add). The causee receives the comitative case,
and causer the agentive.

In both transitive and intransitive clauses, the verb phrase agrees with the
causer.

====
intrans +
_capsize.AUX-PST-CAUS canoe-COM 3S.AN-NOM capsize-AN-3RD_ +
He caused the canoe to capsize.

trans +
_drop.AUX-PST-CAUS 1S-COM axe-ABS my wind-ERG drop-INAN-3RD_ +
The wind made me drop my axe.
====

In the nominative causative, an extra argument is added to the verb
phrase without modifying the valence. The argument is the causer, and
takes the former subject's form (be it nominative or ergative). The
causee, or the argument which was formerly the subject, then takes the
comitative case instead. The verb remains in agreement with the former
subject.

====
*j-a turrayi-j mu nnij-a-m* +
_capsize.aux-pst canoe-nom capsize-inan-3rd_ +
The canoe capsized.

*j-a turrayi-yi nna-j mu nnij-a-m* +
_capsize.aux-pst canoe-com 3s.an-nom capsize-inan-3rd_ +
He caused the canoe to capsize.

*k-a wa-ø wuta-j walu gukarr-u-ø* +
_drop.aux-pst 1s-erg axe-nom my drop-an-1st_ +
I dropped my axe.

*k-a wa-yi wuta-j walu gaju-ø gukarr-u-ø* +
_drop.aux-pst 1s-com axe-nom my wind-erg drop-an-1st_ +
The wind caused me to drop my axe.
====

=== Valence decreasing operations

==== Reflexive/Reciprocal

Ngujari uses a dual analytic/morphological system for reflexives and
reciprocals, which are the same construction.

The personal pronoun of the subject occupies the object position and is
correctly declined, while the auxiliary is marked with the reflex/reciprocal
suffix _naki_ (TODO: add).

====
_carefor.AUX-PRES-REFL Paya-NOM 3S.AN-ACC carefor-AN-3RD_ +
Paya cares for himself.
====

In reflexive constructions, the personal noun is considered to be a pronoun. As
such, the clause is in the nominative-accusative alignment.

The reflexive can be used only for animate subjects. In addition, reciprocals
can further take only plural subjects.

====
_see.AUX-REM-REFL 2PL-NOM see-AN-2ND_ +
You (pl) used to see each other.
====

If the subject of the clause is itself a personal pronoun, the object is
dropped. Hence the reflexive is not necessarily a valence-decreasing operation.

==== Morphological reflexives in possession

When the subject of a VP is the possessor of an object or oblique in the phrase,
the possessed is marked with the reflexive suffix.

====
_3S.AN-ERG ball-ABS-REFL kick-AN-1ST_ +
He kicked his ball.

*maybe*
_ball-ABS-REFL kick-AN-1ST_ +
He kicked his ball.
====

===== Lexical reflexives

If a verb is reflexive by default, the verb will be intransitive and used as
normal, rather than through the analytic/morphological process described above.

// TODO: insert table of examples

==== Antipassive

The antipassive is a valence-decreasing operation. When the patient of a
transitive phrase is to be downplayed, it is omitted. The agent assumes the
absolutive case (usually), or nominative case (with animate pronoun). The verb
is marked with the intransitive modifier _waa_ (TODO: add), as a suffix.

====
_attack.AUX-PST dog-ERG 3S.AN-ABS attack-AN-3RD_ +
The dog attacked him.

_attack.AUX-PST dog-ABS attack-INTRANS-AN-3RD_ +
c.f. The dog attacked (him).
====

// TODO: show example of antipassive used to push RC to adjoined relative clause
// e.g. The dog, [who was attacking]antipassive, barked
