== Voice and valence adjusting operations

=== Valence and predicate calculus

A verb's _valence_ determines the number of arguments it can take. For
example, a verb with a valence of two would take two nouns:

====
_fight.AUX-PST dingo-ERG snake-ABS fight-AN-3RD_ +
The dingo fought the snake.
====

In addition to their valence, the arguments to verbs have restrictions
on their case. For the majority of transitive verbs, with a valence of
two, the arguments take the form of a subject and object. The cases are
determined by the alignment of the sentence.

However, this can differ, and some verbs have irregular argument cases.
This is especially true in the case of verbs relating to movement, which
instead take a subject and a location.

====
_run.aux-pst 1s-erg mountain-loc run-an-1st_ +
I ran to the mountain [and ended up there].
====

// TODO: table of movement words here

When verbs take an argument in the locative case, the speaker can
instead use the revertive or orientative case for further control over
meaning.

====
_run.aux-pst 1s-erg mountain-ori run-an-1st_ +
I ran towards the mountain

_run.aux-pst 1s-erg mountain-rev run-an-1st_ +
I ran away from the mountain
====

All verbs have a _default valence_: the number of arguments it takes
without modification. Most verbs are transitive, but valences can span
between avalent (taking no arguments) and quadrivalent (taking four).

// TODO: example verbs

=== Valence increasing operations

==== Applicatives

For a transitive verb, it is common to find a configuration with a third
argument in an applicative case, representing the means with which the
action occurred. The verb's valency is therefore increased, making it ditransitive.

When using the applicative, the cases of the existing subject and object are unchanged, as is the verb. The only indication of the construction is the presence of the declined third argument.

The applicative cases are:

* instrumental
* comitative
* locative
* orientative
* revertive

====
_stab.aux-pst 3s.an-NOM 3s.an.ch-ACC knife-INSTR stab-3-an_ +
She stabbed the child with a knife
====

==== Causatives

There are two forms of the causative. The _nominative causative_ represents
direct causation when a single noun is responsible for causing a verb phrase to
occur. However, if an entire verb phrase is responsible, or the causation is
more indirect, clause chaining is used.

===== Nominative causative

When a noun phrase is responsible for the action taking place, the nominal
causative is used.

The operation occurs morphologically. The auxiliary of the verb phrase receives
the causative suffix _ji_. The causee receives the comitative case,
and causer the agentive.


In the nominative causative, an extra argument is added to the verb
phrase without modifying the valence. The argument is the causer, and
takes the former subject's form (be it nominative or ergative). The
causee, or the argument which was formerly the subject, then takes the
comitative case instead.

In both transitive and intransitive clauses, the verb phrase agrees with the
causer.

====
_capsize.aux-pst canoe-nom capsize-inan-3rd_ +
The canoe capsized.

_capsize.aux-pst canoe-com 3s.an-nom capsize-an-3rd_ +
He caused the canoe to capsize.

_drop.aux-pst 1s-erg axe-nom drop-an-1st_ +
I dropped the axe.

_drop.aux-pst 1s-com axe-nom wind-erg drop-inan-1st_ +
The wind caused me to drop the axe.
====

=== Valence decreasing operations

==== Reflexive/Reciprocal

Ngujari uses a dual analytic/morphological system for reflexives and
reciprocals, which are the same construction.

The personal pronoun of the subject occupies the object position and is
correctly declined, while the auxiliary is marked with the reflex/reciprocal
suffix _naki_.

====
_carefor.AUX-PRES-REFL Paya-NOM 3S.AN-ACC carefor-AN-3RD_ +
Paya cares for himself.
====

In reflexive constructions, the personal noun is considered to be a pronoun. As
such, the clause is in the nominative-accusative alignment.

The reflexive can be used only for animate subjects. In addition, reciprocals
can further take only plural subjects.

====
_see.AUX-REM-REFL 2PL-NOM see-AN-2ND_ +
You (pl) used to see each other.
====

If the subject of the clause is itself a personal pronoun, the object is
dropped. Hence the reflexive is not necessarily a valence-decreasing operation.

==== Morphological reflexives in possession

When the subject of a VP is the possessor of an object or oblique in the phrase,
the possessed is marked with the reflexive suffix.

====
_3S.AN-ERG ball-ABS-REFL kick-AN-1ST_ +
He kicked his ball.

_ball-ABS-REFL kick-AN-1ST_ +
He kicked his ball.
====

===== Lexical reflexives

If a verb is reflexive by default, the verb will be intransitive and used as
normal, rather than through the analytic/morphological process described above.

// TODO: insert table of examples

==== Antipassive

The antipassive is a valence-decreasing operation. When the patient of a
transitive phrase is to be downplayed, it is omitted. The agent assumes the
absolutive case (usually), or nominative case (with animate pronoun). The verb
is marked with the intransitive suffix _waa_.

====
_attack.AUX-PST dog-ERG 3S.AN-ABS attack-AN-3RD_ +
The dog attacked him.

_attack.AUX-PST dog-ABS attack-INTRANS-AN-3RD_ +
c.f. The dog attacked (him).
====

The antipassive is also used when forming relative clauses for the subject of a sentence, where the relative clause does not have a patient.

Consider this sentence, which uses a postnominal relative clause:

====
_bark.AUX-PST dog-ERG attack.AUX-PST man-ABS attack-3-an bark-AN-3rd_ +
The dog, who was attacking the man, barked
====

Above, the relative clause has a patient (the man). If instead it does not, the relative clause is instead constructed using an adjoined relative clause:

====
_bark.AUX-PST dog-ERG bark-AN-3rd [COMP DEMPRON.AN.S-ERG attack-intrans-3-an]
The dog, who was attacking, barked
====

Note that in most usage, these examples would be expressed using a clause chain. The use of the antipassive in relative clauses is mostly constrained to the written word rather than speech.